<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16660" started-at="2020-07-03T19:54:47 IST" finished-at="2020-07-03T19:55:04 IST">
    <groups>
      <group name="Travel">
        <method signature="LoginPage_Test.LoginPage_test03_failedPassword(java.lang.String, java.lang.String)[pri:0, instance:testCases.LoginPage_Test@4b1c1ea0]" name="LoginPage_test03_failedPassword" class="testCases.LoginPage_Test"/>
      </group> <!-- Travel -->
    </groups>
    <test name="Default test" duration-ms="16660" started-at="2020-07-03T19:54:47 IST" finished-at="2020-07-03T19:55:04 IST">
      <class name="testCases.LoginPage_Test">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testCases.LoginPage_Test@4b1c1ea0]" name="beforeMethod" is-config="true" duration-ms="13858" started-at="2020-07-03T19:54:49 IST" finished-at="2020-07-03T19:55:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="LoginPage_test03_failedPassword(java.lang.String, java.lang.String)[pri:0, instance:testCases.LoginPage_Test@4b1c1ea0]" name="LoginPage_test03_failedPassword" duration-ms="76" started-at="2020-07-03T19:55:03 IST" data-provider="TravelData" finished-at="2020-07-03T19:55:03 IST">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy10.sendKeys(Unknown Source)
at testCases.LoginPage_Test.LoginPage_test03_failedPassword(LoginPage_Test.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginPage_test03_failedPassword -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testCases.LoginPage_Test@4b1c1ea0]" name="afterMethod" is-config="true" duration-ms="883" started-at="2020-07-03T19:55:03 IST" finished-at="2020-07-03T19:55:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testCases.LoginPage_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
